# Generated by Django 4.2.5 on 2023-10-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="yorum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yorum", models.TextField(max_length=1000)),
                ("yorum_basligi", models.TextField(max_length=200)),
                ("spoiler", models.BooleanField(default=False)),
                ("yorum_yapilan_film_id", models.IntegerField()),
            ],
        ),
    ]
