# Generated by Django 4.2.5 on 2023-10-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="yorumlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yorum", models.TextField(max_length=1000)),
                ("yorum_basligi", models.TextField(max_length=200)),
                ("spoiler", models.BooleanField(default=False)),
                ("yorum_yapilan_film_id", models.IntegerField()),
                ("yorum_yapan_kullanici_adi", models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="yorum",
        ),
    ]
